### ISSUE TITLE
ArgumentParser 1.0

### ISSUE THREAD

**Issue by notpeelz** [LouisTakePILLz/ArgumentParser#1]
Those are the features to be implemented before reaching the stable release.

The features listed below are subject to change and more will be added as new features (or bug fixes) are proposed.
## Tasks
- [x] Support for reflection-driven parsing
- [ ] Improve exception handling (especially for binding)
- [x] Support for special value (i.e. flags) handling
- [x] Flag value aggregation
- [x] Support for trailing values parsing
- [ ] Make _actual_ test units (#4)
- [ ] Add help-writing _helpers_
- [x] Migrate argument creation process to `IOptionAttribute` 
- [x] Migrate `ParameterPair` creation process to `IArgument`
- [x] Support per-argument ~~detokenizer~~ preprocessor delegate

Please refrain from submitting feature proposals here; however, feel free to open a new issue.
